// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package model

import (
	fmt "fmt"
	simplcrypto "github.com/cohix/simplcrypto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Meta                 *TaskMeta            `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	UUID                 string               `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Kind                 string               `protobuf:"bytes,3,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Status               string               `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	EncBody              *simplcrypto.Message `protobuf:"bytes,5,opt,name=EncBody,proto3" json:"EncBody,omitempty"`
	EncResult            *simplcrypto.Message `protobuf:"bytes,6,opt,name=EncResult,proto3" json:"EncResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetMeta() *TaskMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Task) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Task) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Task) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Task) GetEncBody() *simplcrypto.Message {
	if m != nil {
		return m.EncBody
	}
	return nil
}

func (m *Task) GetEncResult() *simplcrypto.Message {
	if m != nil {
		return m.EncResult
	}
	return nil
}

type TaskMeta struct {
	Annotations          []string             `protobuf:"bytes,1,rep,name=Annotations,proto3" json:"Annotations,omitempty"`
	RunnerUUID           string               `protobuf:"bytes,2,opt,name=RunnerUUID,proto3" json:"RunnerUUID,omitempty"`
	ChildRunnerUUID      string               `protobuf:"bytes,3,opt,name=ChildRunnerUUID,proto3" json:"ChildRunnerUUID,omitempty"`
	MasterEncTaskKey     *simplcrypto.Message `protobuf:"bytes,4,opt,name=MasterEncTaskKey,proto3" json:"MasterEncTaskKey,omitempty"`
	RunnerEncTaskKey     *simplcrypto.Message `protobuf:"bytes,5,opt,name=RunnerEncTaskKey,proto3" json:"RunnerEncTaskKey,omitempty"`
	ClientEncTaskKey     *simplcrypto.Message `protobuf:"bytes,6,opt,name=ClientEncTaskKey,proto3" json:"ClientEncTaskKey,omitempty"`
	RetrySeconds         int32                `protobuf:"varint,7,opt,name=RetrySeconds,proto3" json:"RetrySeconds,omitempty"`
	TimeoutSeconds       int32                `protobuf:"varint,8,opt,name=TimeoutSeconds,proto3" json:"TimeoutSeconds,omitempty"`
	Version              int32                `protobuf:"varint,9,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskMeta) Reset()         { *m = TaskMeta{} }
func (m *TaskMeta) String() string { return proto.CompactTextString(m) }
func (*TaskMeta) ProtoMessage()    {}
func (*TaskMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *TaskMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskMeta.Unmarshal(m, b)
}
func (m *TaskMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskMeta.Marshal(b, m, deterministic)
}
func (m *TaskMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskMeta.Merge(m, src)
}
func (m *TaskMeta) XXX_Size() int {
	return xxx_messageInfo_TaskMeta.Size(m)
}
func (m *TaskMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TaskMeta proto.InternalMessageInfo

func (m *TaskMeta) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *TaskMeta) GetRunnerUUID() string {
	if m != nil {
		return m.RunnerUUID
	}
	return ""
}

func (m *TaskMeta) GetChildRunnerUUID() string {
	if m != nil {
		return m.ChildRunnerUUID
	}
	return ""
}

func (m *TaskMeta) GetMasterEncTaskKey() *simplcrypto.Message {
	if m != nil {
		return m.MasterEncTaskKey
	}
	return nil
}

func (m *TaskMeta) GetRunnerEncTaskKey() *simplcrypto.Message {
	if m != nil {
		return m.RunnerEncTaskKey
	}
	return nil
}

func (m *TaskMeta) GetClientEncTaskKey() *simplcrypto.Message {
	if m != nil {
		return m.ClientEncTaskKey
	}
	return nil
}

func (m *TaskMeta) GetRetrySeconds() int32 {
	if m != nil {
		return m.RetrySeconds
	}
	return 0
}

func (m *TaskMeta) GetTimeoutSeconds() int32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

func (m *TaskMeta) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type TaskUpdate struct {
	UUID                 string               `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EncResult            *simplcrypto.Message `protobuf:"bytes,3,opt,name=EncResult,proto3" json:"EncResult,omitempty"`
	RunnerEncTaskKey     *simplcrypto.Message `protobuf:"bytes,4,opt,name=RunnerEncTaskKey,proto3" json:"RunnerEncTaskKey,omitempty"`
	RunnerUUID           string               `protobuf:"bytes,5,opt,name=RunnerUUID,proto3" json:"RunnerUUID,omitempty"`
	ChildRunnerUUID      string               `protobuf:"bytes,6,opt,name=ChildRunnerUUID,proto3" json:"ChildRunnerUUID,omitempty"`
	RetrySeconds         int32                `protobuf:"varint,7,opt,name=RetrySeconds,proto3" json:"RetrySeconds,omitempty"`
	Version              int32                `protobuf:"varint,8,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskUpdate) Reset()         { *m = TaskUpdate{} }
func (m *TaskUpdate) String() string { return proto.CompactTextString(m) }
func (*TaskUpdate) ProtoMessage()    {}
func (*TaskUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *TaskUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskUpdate.Unmarshal(m, b)
}
func (m *TaskUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskUpdate.Marshal(b, m, deterministic)
}
func (m *TaskUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskUpdate.Merge(m, src)
}
func (m *TaskUpdate) XXX_Size() int {
	return xxx_messageInfo_TaskUpdate.Size(m)
}
func (m *TaskUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TaskUpdate proto.InternalMessageInfo

func (m *TaskUpdate) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *TaskUpdate) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TaskUpdate) GetEncResult() *simplcrypto.Message {
	if m != nil {
		return m.EncResult
	}
	return nil
}

func (m *TaskUpdate) GetRunnerEncTaskKey() *simplcrypto.Message {
	if m != nil {
		return m.RunnerEncTaskKey
	}
	return nil
}

func (m *TaskUpdate) GetRunnerUUID() string {
	if m != nil {
		return m.RunnerUUID
	}
	return ""
}

func (m *TaskUpdate) GetChildRunnerUUID() string {
	if m != nil {
		return m.ChildRunnerUUID
	}
	return ""
}

func (m *TaskUpdate) GetRetrySeconds() int32 {
	if m != nil {
		return m.RetrySeconds
	}
	return 0
}

func (m *TaskUpdate) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*Task)(nil), "taask.server.model.Task")
	proto.RegisterType((*TaskMeta)(nil), "taask.server.model.TaskMeta")
	proto.RegisterType((*TaskUpdate)(nil), "taask.server.model.TaskUpdate")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0xd6, 0x34, 0x6d, 0xef, 0x10, 0x20, 0x4b, 0x4c, 0x16, 0x42, 0x28, 0x2a, 0x02, 0xe5,
	0x85, 0x64, 0x62, 0x5f, 0xb0, 0x8d, 0x3e, 0xa0, 0xa9, 0x2f, 0xd9, 0xca, 0x03, 0x6f, 0x5e, 0x62,
	0xad, 0xd6, 0x12, 0xbb, 0xb2, 0x6f, 0x10, 0xfd, 0x20, 0xfe, 0x81, 0xaf, 0xe1, 0x5b, 0x90, 0xed,
	0x15, 0xdc, 0xa5, 0x54, 0xdd, 0x4b, 0x95, 0x7b, 0x74, 0x7c, 0x7c, 0x7c, 0x7a, 0x2e, 0x00, 0x32,
	0x73, 0x9f, 0xaf, 0xb4, 0x42, 0x45, 0x08, 0x32, 0x3b, 0x18, 0xae, 0xbf, 0x73, 0x9d, 0xb7, 0xaa,
	0xe6, 0xcd, 0xeb, 0xd3, 0x3b, 0x81, 0xcb, 0xee, 0x36, 0xaf, 0x54, 0x5b, 0x54, 0x6a, 0x29, 0x7e,
	0x14, 0x46, 0xb4, 0xab, 0xa6, 0xd2, 0xeb, 0x15, 0xaa, 0xc2, 0x9d, 0x2b, 0x5a, 0x6e, 0x0c, 0xbb,
	0xe3, 0x5e, 0x65, 0xfa, 0x3b, 0x82, 0xf8, 0x86, 0x99, 0x7b, 0x72, 0x0a, 0xf1, 0x9c, 0x23, 0xa3,
	0x51, 0x1a, 0x65, 0xc7, 0x9f, 0xde, 0xe4, 0x7d, 0xf5, 0xdc, 0xf2, 0x2c, 0xa7, 0x74, 0x4c, 0x42,
	0x20, 0x5e, 0x2c, 0xbe, 0x7c, 0xa6, 0x47, 0x69, 0x94, 0x4d, 0x4a, 0xf7, 0x6d, 0xb1, 0x2b, 0x21,
	0x6b, 0x3a, 0xf0, 0x98, 0xfd, 0x26, 0x27, 0x90, 0x5c, 0x23, 0xc3, 0xce, 0xd0, 0xd8, 0xa1, 0x0f,
	0x13, 0x29, 0x60, 0x34, 0x93, 0xd5, 0x85, 0xaa, 0xd7, 0x74, 0xe8, 0x2e, 0x7d, 0x95, 0x3b, 0xb7,
	0xb9, 0xb7, 0x9b, 0xcf, 0xbd, 0xd1, 0x72, 0xc3, 0x22, 0x67, 0x30, 0x99, 0xc9, 0xaa, 0xe4, 0xa6,
	0x6b, 0x90, 0x26, 0xfb, 0x8e, 0xfc, 0xe3, 0x4d, 0x7f, 0x0e, 0x60, 0xbc, 0x31, 0x4e, 0x52, 0x38,
	0x3e, 0x97, 0x52, 0x21, 0x43, 0xa1, 0xa4, 0xa1, 0x51, 0x3a, 0xc8, 0x26, 0x65, 0x08, 0x91, 0xb7,
	0x00, 0x65, 0x27, 0x25, 0xd7, 0xc1, 0xd3, 0x02, 0x84, 0x64, 0xf0, 0xe2, 0x72, 0x29, 0x9a, 0x3a,
	0x20, 0xf9, 0xb7, 0x3e, 0x86, 0xc9, 0x39, 0xbc, 0x9c, 0x33, 0x83, 0x5c, 0xcf, 0x64, 0x65, 0x0d,
	0x5c, 0xf1, 0xb5, 0x0b, 0xe0, 0xbf, 0xa6, 0x7b, 0x74, 0x2b, 0xe1, 0x05, 0x03, 0x89, 0xbd, 0x51,
	0xf5, 0xe8, 0x56, 0xe2, 0xb2, 0x11, 0x5c, 0x62, 0x20, 0xb1, 0x37, 0xba, 0x1e, 0x9d, 0x4c, 0xe1,
	0x59, 0xc9, 0x51, 0xaf, 0xaf, 0x79, 0xa5, 0x64, 0x6d, 0xe8, 0x28, 0x8d, 0xb2, 0x61, 0xb9, 0x85,
	0x91, 0x0f, 0xf0, 0xfc, 0x46, 0xb4, 0x5c, 0x75, 0xb8, 0x61, 0x8d, 0x1d, 0xeb, 0x11, 0x4a, 0x28,
	0x8c, 0xbe, 0x72, 0x6d, 0x84, 0x92, 0x74, 0xe2, 0x08, 0x9b, 0x71, 0xfa, 0xeb, 0x08, 0xc0, 0xde,
	0xb8, 0x58, 0xd5, 0x0c, 0xf9, 0xdf, 0x72, 0x45, 0x41, 0xb9, 0x4e, 0x20, 0x31, 0xbe, 0x48, 0xfe,
	0x7f, 0x79, 0x98, 0xb6, 0x7b, 0x31, 0x38, 0xac, 0x17, 0x3b, 0xb3, 0x8d, 0x9f, 0x96, 0xed, 0x76,
	0x57, 0x86, 0x87, 0x74, 0x25, 0xd9, 0xdd, 0x95, 0x43, 0x22, 0x0e, 0xa2, 0x1b, 0x6f, 0x45, 0x77,
	0xf1, 0xfe, 0xdb, 0xbb, 0x60, 0xef, 0xdd, 0xe2, 0xfa, 0xdf, 0x8f, 0x7e, 0x7d, 0x0b, 0xb7, 0xbe,
	0xb7, 0x89, 0xdb, 0xf8, 0xb3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x09, 0x91, 0xa3, 0xf2, 0x45,
	0x04, 0x00, 0x00,
}
