// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	crypto "github.com/taask/taask-server/crypto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	UUID                 string                     `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Type                 string                     `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	PubKey               *crypto.SerializablePubKey `protobuf:"bytes,3,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Body                 []byte                     `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Task) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Task) GetPubKey() *crypto.SerializablePubKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Task) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type TaskResult struct {
	UUID                 string          `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	EncResponse          *crypto.Message `protobuf:"bytes,2,opt,name=EncResponse,proto3" json:"EncResponse,omitempty"`
	EncResponseSymKey    *crypto.Message `protobuf:"bytes,3,opt,name=EncResponseSymKey,proto3" json:"EncResponseSymKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TaskResult) Reset()         { *m = TaskResult{} }
func (m *TaskResult) String() string { return proto.CompactTextString(m) }
func (*TaskResult) ProtoMessage()    {}
func (*TaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *TaskResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResult.Unmarshal(m, b)
}
func (m *TaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResult.Marshal(b, m, deterministic)
}
func (m *TaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResult.Merge(m, src)
}
func (m *TaskResult) XXX_Size() int {
	return xxx_messageInfo_TaskResult.Size(m)
}
func (m *TaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResult proto.InternalMessageInfo

func (m *TaskResult) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *TaskResult) GetEncResponse() *crypto.Message {
	if m != nil {
		return m.EncResponse
	}
	return nil
}

func (m *TaskResult) GetEncResponseSymKey() *crypto.Message {
	if m != nil {
		return m.EncResponseSymKey
	}
	return nil
}

type QueueTaskResponse struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueTaskResponse) Reset()         { *m = QueueTaskResponse{} }
func (m *QueueTaskResponse) String() string { return proto.CompactTextString(m) }
func (*QueueTaskResponse) ProtoMessage()    {}
func (*QueueTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *QueueTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueTaskResponse.Unmarshal(m, b)
}
func (m *QueueTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueTaskResponse.Marshal(b, m, deterministic)
}
func (m *QueueTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueTaskResponse.Merge(m, src)
}
func (m *QueueTaskResponse) XXX_Size() int {
	return xxx_messageInfo_QueueTaskResponse.Size(m)
}
func (m *QueueTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueTaskResponse proto.InternalMessageInfo

func (m *QueueTaskResponse) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type CheckTaskRequest struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTaskRequest) Reset()         { *m = CheckTaskRequest{} }
func (m *CheckTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CheckTaskRequest) ProtoMessage()    {}
func (*CheckTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *CheckTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTaskRequest.Unmarshal(m, b)
}
func (m *CheckTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTaskRequest.Marshal(b, m, deterministic)
}
func (m *CheckTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTaskRequest.Merge(m, src)
}
func (m *CheckTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CheckTaskRequest.Size(m)
}
func (m *CheckTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTaskRequest proto.InternalMessageInfo

func (m *CheckTaskRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type CheckTaskResponse struct {
	Completed            bool        `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Progress             int32       `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Result               *TaskResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CheckTaskResponse) Reset()         { *m = CheckTaskResponse{} }
func (m *CheckTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CheckTaskResponse) ProtoMessage()    {}
func (*CheckTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *CheckTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTaskResponse.Unmarshal(m, b)
}
func (m *CheckTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTaskResponse.Marshal(b, m, deterministic)
}
func (m *CheckTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTaskResponse.Merge(m, src)
}
func (m *CheckTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CheckTaskResponse.Size(m)
}
func (m *CheckTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTaskResponse proto.InternalMessageInfo

func (m *CheckTaskResponse) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *CheckTaskResponse) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *CheckTaskResponse) GetResult() *TaskResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "taask.server.model.Task")
	proto.RegisterType((*TaskResult)(nil), "taask.server.model.TaskResult")
	proto.RegisterType((*QueueTaskResponse)(nil), "taask.server.model.QueueTaskResponse")
	proto.RegisterType((*CheckTaskRequest)(nil), "taask.server.model.CheckTaskRequest")
	proto.RegisterType((*CheckTaskResponse)(nil), "taask.server.model.CheckTaskResponse")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0x5a, 0x4b, 0x3b, 0xf5, 0x60, 0xf7, 0x14, 0x4a, 0x91, 0x12, 0xd1, 0xf6, 0x62, 0x02,
	0x15, 0x3c, 0x2a, 0x54, 0x3d, 0xa8, 0x08, 0xba, 0xb6, 0x17, 0x6f, 0x9b, 0x74, 0x68, 0x43, 0x92,
	0xee, 0xba, 0xbb, 0x11, 0xe2, 0x55, 0xfc, 0x1b, 0x3f, 0x52, 0xb2, 0x1b, 0x6c, 0xb5, 0xc1, 0xcb,
	0x32, 0x33, 0xfb, 0xde, 0xcc, 0x7b, 0xc3, 0x00, 0x68, 0xa6, 0x12, 0x5f, 0x48, 0xae, 0x39, 0x21,
	0x9a, 0x95, 0x89, 0x42, 0xf9, 0x86, 0xd2, 0xcf, 0xf8, 0x1c, 0xd3, 0x5e, 0x2f, 0x92, 0x85, 0xd0,
	0x3c, 0x30, 0x88, 0x20, 0x43, 0xa5, 0xd8, 0x02, 0x2d, 0xfe, 0xcf, 0x5f, 0x82, 0x85, 0x60, 0xb1,
	0xb4, 0x7f, 0xde, 0x87, 0x03, 0x8d, 0x29, 0x53, 0x09, 0x21, 0xd0, 0x98, 0xcd, 0x6e, 0xaf, 0x5d,
	0x67, 0xe0, 0x8c, 0xda, 0xd4, 0xc4, 0x65, 0x6d, 0x5a, 0x08, 0x74, 0x77, 0x6c, 0xad, 0x8c, 0xc9,
	0x25, 0x34, 0x1f, 0xf3, 0xf0, 0x1e, 0x0b, 0x77, 0x77, 0xe0, 0x8c, 0x3a, 0xe3, 0xa1, 0xff, 0x4b,
	0x8d, 0x1d, 0x55, 0x66, 0x31, 0x4b, 0xe3, 0x77, 0x16, 0xa6, 0x68, 0xe1, 0xb4, 0xa2, 0x95, 0x4d,
	0x27, 0x7c, 0x5e, 0xb8, 0x8d, 0x81, 0x33, 0xda, 0xa7, 0x26, 0xf6, 0xbe, 0x1c, 0x80, 0x52, 0x05,
	0x45, 0x95, 0xa7, 0xba, 0x56, 0xcb, 0x05, 0x74, 0x6e, 0x56, 0x11, 0x45, 0x25, 0xf8, 0x4a, 0x59,
	0x49, 0x9d, 0x71, 0xbf, 0x76, 0xf8, 0x83, 0x75, 0x4f, 0x37, 0x09, 0xe4, 0x0e, 0xba, 0x1b, 0xe9,
	0x73, 0x91, 0xad, 0x2d, 0xfc, 0xdf, 0x65, 0x9b, 0xe6, 0x0d, 0xa1, 0xfb, 0x94, 0x63, 0x8e, 0x95,
	0x64, 0x3b, 0xa0, 0x46, 0xb4, 0x77, 0x02, 0x07, 0x57, 0x4b, 0x8c, 0x12, 0x0b, 0x7c, 0xcd, 0x51,
	0xd5, 0x9a, 0xf3, 0x3e, 0x1d, 0xe8, 0x6e, 0x00, 0xab, 0x8e, 0x7d, 0x68, 0x47, 0x3c, 0x13, 0x29,
	0x6a, 0x9c, 0x1b, 0x78, 0x8b, 0xae, 0x0b, 0xa4, 0x07, 0x2d, 0x21, 0xf9, 0x42, 0xa2, 0x52, 0x66,
	0x1b, 0x7b, 0xf4, 0x27, 0x27, 0xe7, 0xd0, 0x94, 0x66, 0x95, 0x95, 0xc3, 0x43, 0x7f, 0xfb, 0x64,
	0xfc, 0xf5, 0xc2, 0x69, 0x85, 0x9e, 0x1c, 0xbf, 0x1c, 0x2d, 0x62, 0xbd, 0xcc, 0x43, 0x3f, 0xe2,
	0x59, 0x60, 0x38, 0xf6, 0x3d, 0xb5, 0xcc, 0xc0, 0x30, 0xc3, 0xa6, 0xb9, 0x9d, 0xb3, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xec, 0x42, 0x84, 0x1d, 0x95, 0x02, 0x00, 0x00,
}
