// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package model

import (
	fmt "fmt"
	simplcrypto "github.com/cohix/simplcrypto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Meta                 *TaskMeta            `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	UUID                 string               `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Kind                 string               `protobuf:"bytes,3,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Body                 []byte               `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
	Status               string               `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	EncResult            *simplcrypto.Message `protobuf:"bytes,6,opt,name=EncResult,proto3" json:"EncResult,omitempty"`
	EncResultSymKey      *simplcrypto.Message `protobuf:"bytes,7,opt,name=EncResultSymKey,proto3" json:"EncResultSymKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetMeta() *TaskMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Task) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Task) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Task) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Task) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Task) GetEncResult() *simplcrypto.Message {
	if m != nil {
		return m.EncResult
	}
	return nil
}

func (m *Task) GetEncResultSymKey() *simplcrypto.Message {
	if m != nil {
		return m.EncResultSymKey
	}
	return nil
}

type TaskMeta struct {
	Annotations          []string                        `protobuf:"bytes,1,rep,name=Annotations,proto3" json:"Annotations,omitempty"`
	RunnerUUID           string                          `protobuf:"bytes,2,opt,name=RunnerUUID,proto3" json:"RunnerUUID,omitempty"`
	ChildRunnerUUID      string                          `protobuf:"bytes,3,opt,name=ChildRunnerUUID,proto3" json:"ChildRunnerUUID,omitempty"`
	ResultPubKey         *simplcrypto.SerializablePubKey `protobuf:"bytes,4,opt,name=ResultPubKey,proto3" json:"ResultPubKey,omitempty"`
	ResultToken          string                          `protobuf:"bytes,5,opt,name=ResultToken,proto3" json:"ResultToken,omitempty"`
	RetrySeconds         int32                           `protobuf:"varint,6,opt,name=RetrySeconds,proto3" json:"RetrySeconds,omitempty"`
	TimeoutSeconds       int32                           `protobuf:"varint,7,opt,name=TimeoutSeconds,proto3" json:"TimeoutSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *TaskMeta) Reset()         { *m = TaskMeta{} }
func (m *TaskMeta) String() string { return proto.CompactTextString(m) }
func (*TaskMeta) ProtoMessage()    {}
func (*TaskMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *TaskMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskMeta.Unmarshal(m, b)
}
func (m *TaskMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskMeta.Marshal(b, m, deterministic)
}
func (m *TaskMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskMeta.Merge(m, src)
}
func (m *TaskMeta) XXX_Size() int {
	return xxx_messageInfo_TaskMeta.Size(m)
}
func (m *TaskMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TaskMeta proto.InternalMessageInfo

func (m *TaskMeta) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *TaskMeta) GetRunnerUUID() string {
	if m != nil {
		return m.RunnerUUID
	}
	return ""
}

func (m *TaskMeta) GetChildRunnerUUID() string {
	if m != nil {
		return m.ChildRunnerUUID
	}
	return ""
}

func (m *TaskMeta) GetResultPubKey() *simplcrypto.SerializablePubKey {
	if m != nil {
		return m.ResultPubKey
	}
	return nil
}

func (m *TaskMeta) GetResultToken() string {
	if m != nil {
		return m.ResultToken
	}
	return ""
}

func (m *TaskMeta) GetRetrySeconds() int32 {
	if m != nil {
		return m.RetrySeconds
	}
	return 0
}

func (m *TaskMeta) GetTimeoutSeconds() int32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

type QueueTaskResponse struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueTaskResponse) Reset()         { *m = QueueTaskResponse{} }
func (m *QueueTaskResponse) String() string { return proto.CompactTextString(m) }
func (*QueueTaskResponse) ProtoMessage()    {}
func (*QueueTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *QueueTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueTaskResponse.Unmarshal(m, b)
}
func (m *QueueTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueTaskResponse.Marshal(b, m, deterministic)
}
func (m *QueueTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueTaskResponse.Merge(m, src)
}
func (m *QueueTaskResponse) XXX_Size() int {
	return xxx_messageInfo_QueueTaskResponse.Size(m)
}
func (m *QueueTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueTaskResponse proto.InternalMessageInfo

func (m *QueueTaskResponse) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type CheckTaskRequest struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTaskRequest) Reset()         { *m = CheckTaskRequest{} }
func (m *CheckTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CheckTaskRequest) ProtoMessage()    {}
func (*CheckTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *CheckTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTaskRequest.Unmarshal(m, b)
}
func (m *CheckTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTaskRequest.Marshal(b, m, deterministic)
}
func (m *CheckTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTaskRequest.Merge(m, src)
}
func (m *CheckTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CheckTaskRequest.Size(m)
}
func (m *CheckTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTaskRequest proto.InternalMessageInfo

func (m *CheckTaskRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type CheckTaskResponse struct {
	Status               string      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Progress             int32       `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Result               *TaskUpdate `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CheckTaskResponse) Reset()         { *m = CheckTaskResponse{} }
func (m *CheckTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CheckTaskResponse) ProtoMessage()    {}
func (*CheckTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *CheckTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTaskResponse.Unmarshal(m, b)
}
func (m *CheckTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTaskResponse.Marshal(b, m, deterministic)
}
func (m *CheckTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTaskResponse.Merge(m, src)
}
func (m *CheckTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CheckTaskResponse.Size(m)
}
func (m *CheckTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTaskResponse proto.InternalMessageInfo

func (m *CheckTaskResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CheckTaskResponse) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *CheckTaskResponse) GetResult() *TaskUpdate {
	if m != nil {
		return m.Result
	}
	return nil
}

type TaskUpdate struct {
	UUID                 string               `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EncResult            *simplcrypto.Message `protobuf:"bytes,3,opt,name=EncResult,proto3" json:"EncResult,omitempty"`
	EncResultSymKey      *simplcrypto.Message `protobuf:"bytes,4,opt,name=EncResultSymKey,proto3" json:"EncResultSymKey,omitempty"`
	ResultToken          string               `protobuf:"bytes,5,opt,name=ResultToken,proto3" json:"ResultToken,omitempty"`
	RunnerUUID           string               `protobuf:"bytes,6,opt,name=RunnerUUID,proto3" json:"RunnerUUID,omitempty"`
	RetrySeconds         int32                `protobuf:"varint,7,opt,name=RetrySeconds,proto3" json:"RetrySeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskUpdate) Reset()         { *m = TaskUpdate{} }
func (m *TaskUpdate) String() string { return proto.CompactTextString(m) }
func (*TaskUpdate) ProtoMessage()    {}
func (*TaskUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{5}
}

func (m *TaskUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskUpdate.Unmarshal(m, b)
}
func (m *TaskUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskUpdate.Marshal(b, m, deterministic)
}
func (m *TaskUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskUpdate.Merge(m, src)
}
func (m *TaskUpdate) XXX_Size() int {
	return xxx_messageInfo_TaskUpdate.Size(m)
}
func (m *TaskUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TaskUpdate proto.InternalMessageInfo

func (m *TaskUpdate) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *TaskUpdate) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TaskUpdate) GetEncResult() *simplcrypto.Message {
	if m != nil {
		return m.EncResult
	}
	return nil
}

func (m *TaskUpdate) GetEncResultSymKey() *simplcrypto.Message {
	if m != nil {
		return m.EncResultSymKey
	}
	return nil
}

func (m *TaskUpdate) GetResultToken() string {
	if m != nil {
		return m.ResultToken
	}
	return ""
}

func (m *TaskUpdate) GetRunnerUUID() string {
	if m != nil {
		return m.RunnerUUID
	}
	return ""
}

func (m *TaskUpdate) GetRetrySeconds() int32 {
	if m != nil {
		return m.RetrySeconds
	}
	return 0
}

func init() {
	proto.RegisterType((*Task)(nil), "taask.server.model.Task")
	proto.RegisterType((*TaskMeta)(nil), "taask.server.model.TaskMeta")
	proto.RegisterType((*QueueTaskResponse)(nil), "taask.server.model.QueueTaskResponse")
	proto.RegisterType((*CheckTaskRequest)(nil), "taask.server.model.CheckTaskRequest")
	proto.RegisterType((*CheckTaskResponse)(nil), "taask.server.model.CheckTaskResponse")
	proto.RegisterType((*TaskUpdate)(nil), "taask.server.model.TaskUpdate")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x51, 0x6f, 0xd3, 0x30,
	0x14, 0x85, 0x95, 0x36, 0x4d, 0xd7, 0xbb, 0x89, 0x31, 0x4b, 0x4c, 0xd1, 0x84, 0xa6, 0x28, 0x88,
	0xd1, 0x17, 0xd2, 0x89, 0x49, 0xbc, 0x22, 0xb6, 0xf1, 0x80, 0xa6, 0x49, 0xe0, 0xb6, 0x2f, 0xbc,
	0xb9, 0xc9, 0x55, 0x1b, 0x35, 0x89, 0x83, 0xed, 0x20, 0xc2, 0x0b, 0x12, 0xbf, 0x81, 0x5f, 0xc1,
	0xaf, 0x44, 0xb6, 0xbb, 0x36, 0x69, 0x07, 0x1a, 0xbc, 0x54, 0xbe, 0x47, 0x9f, 0xd3, 0x73, 0x4f,
	0x8e, 0x02, 0xa0, 0x98, 0x5c, 0x46, 0xa5, 0xe0, 0x8a, 0x13, 0xa2, 0x98, 0x1e, 0x24, 0x8a, 0x2f,
	0x28, 0xa2, 0x9c, 0x27, 0x98, 0x9d, 0x9c, 0xcf, 0x53, 0xb5, 0xa8, 0x66, 0x51, 0xcc, 0xf3, 0x51,
	0xcc, 0x17, 0xe9, 0xd7, 0x91, 0x4c, 0xf3, 0x32, 0x8b, 0x45, 0x5d, 0x2a, 0x3e, 0x32, 0xf7, 0x46,
	0x39, 0x4a, 0xc9, 0xe6, 0x68, 0x9f, 0xf2, 0xa0, 0x1b, 0x4b, 0xac, 0x4b, 0x96, 0x0a, 0x7b, 0x23,
	0xfc, 0xd1, 0x01, 0x77, 0xc2, 0xe4, 0x92, 0x9c, 0x83, 0x7b, 0x8b, 0x8a, 0xf9, 0x4e, 0xe0, 0x0c,
	0xf7, 0x5f, 0x3d, 0x8d, 0x76, 0xfd, 0x44, 0x9a, 0xd3, 0x0c, 0x35, 0x24, 0x21, 0xe0, 0x4e, 0xa7,
	0xef, 0xaf, 0xfd, 0x4e, 0xe0, 0x0c, 0x07, 0xd4, 0x9c, 0xb5, 0x76, 0x93, 0x16, 0x89, 0xdf, 0xb5,
	0x9a, 0x3e, 0x6b, 0xed, 0x92, 0x27, 0xb5, 0xef, 0x06, 0xce, 0xf0, 0x80, 0x9a, 0x33, 0x39, 0x06,
	0x6f, 0xac, 0x98, 0xaa, 0xa4, 0xdf, 0x33, 0xe4, 0x6a, 0x22, 0x17, 0x30, 0x78, 0x57, 0xc4, 0x14,
	0x65, 0x95, 0x29, 0xdf, 0x33, 0x56, 0x9e, 0x44, 0x66, 0x87, 0xc8, 0x2e, 0x11, 0xdd, 0xda, 0x85,
	0xe9, 0x86, 0x23, 0x6f, 0xe0, 0x70, 0x3d, 0x8c, 0xeb, 0xfc, 0x06, 0x6b, 0xbf, 0xff, 0xb7, 0xab,
	0xdb, 0x74, 0xf8, 0xab, 0x03, 0x7b, 0x77, 0xcb, 0x91, 0x00, 0xf6, 0xdf, 0x16, 0x05, 0x57, 0x4c,
	0xa5, 0xbc, 0x90, 0xbe, 0x13, 0x74, 0x87, 0x03, 0xda, 0x94, 0xc8, 0x29, 0x00, 0xad, 0x8a, 0x02,
	0x45, 0x63, 0xfd, 0x86, 0x42, 0x86, 0x70, 0x78, 0xb5, 0x48, 0xb3, 0xa4, 0x01, 0xd9, 0x3c, 0xb6,
	0x65, 0x72, 0x0d, 0x07, 0xd6, 0xc8, 0x87, 0x6a, 0xa6, 0x6d, 0xbb, 0xc6, 0x76, 0xd0, 0xb6, 0x3d,
	0x46, 0x91, 0xb2, 0x2c, 0xfd, 0xc6, 0x66, 0x19, 0x5a, 0x8e, 0xb6, 0x6e, 0x69, 0xc7, 0x76, 0x9e,
	0xf0, 0x25, 0x16, 0xab, 0x44, 0x9b, 0x12, 0x09, 0xf5, 0xff, 0x28, 0x51, 0x8f, 0x31, 0xe6, 0x45,
	0x22, 0x4d, 0xb2, 0x3d, 0xda, 0xd2, 0xc8, 0x19, 0x3c, 0x9a, 0xa4, 0x39, 0xf2, 0x4a, 0xdd, 0x51,
	0x7d, 0x43, 0x6d, 0xa9, 0xe1, 0x0b, 0x38, 0xfa, 0x58, 0x61, 0x85, 0x3a, 0x30, 0x8a, 0xb2, 0xe4,
	0x85, 0xc4, 0x75, 0x17, 0x9c, 0x4d, 0x17, 0xc2, 0x33, 0x78, 0x7c, 0xb5, 0xc0, 0x78, 0x69, 0xc1,
	0xcf, 0x15, 0x4a, 0x75, 0x2f, 0xf7, 0x1d, 0x8e, 0x1a, 0xdc, 0xea, 0x81, 0xc7, 0xe0, 0x49, 0x5b,
	0x10, 0x8b, 0xae, 0x26, 0x72, 0x02, 0x7b, 0xa5, 0xe0, 0x73, 0x81, 0x52, 0x9a, 0xe4, 0x7b, 0x74,
	0x3d, 0x93, 0xd7, 0xe0, 0x09, 0xdb, 0x9c, 0xae, 0xc9, 0xf1, 0xf4, 0x4f, 0x25, 0x9e, 0x96, 0x09,
	0x53, 0x48, 0x57, 0x74, 0xf8, 0xb3, 0x03, 0xb0, 0x91, 0xef, 0xf3, 0xd8, 0xb0, 0xd3, 0x69, 0xd9,
	0x69, 0xf5, 0xb5, 0xfb, 0xff, 0x7d, 0x75, 0xff, 0xa5, 0xaf, 0x0f, 0x78, 0xe1, 0xed, 0x8a, 0x7a,
	0x3b, 0x15, 0xdd, 0x2e, 0x44, 0x7f, 0xb7, 0x10, 0x97, 0xcf, 0x3f, 0x3d, 0x6b, 0x7c, 0x4e, 0x4c,
	0x94, 0xf6, 0xf7, 0xa5, 0x0d, 0x74, 0x64, 0x02, 0x9d, 0x79, 0xe6, 0x43, 0x72, 0xf1, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0xbd, 0xaf, 0xed, 0x0b, 0xce, 0x04, 0x00, 0x00,
}
