// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package service

import (
	fmt "fmt"
	simplcrypto "github.com/cohix/simplcrypto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthMemberRequest struct {
	UUID                 string                          `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	GroupUUID            string                          `protobuf:"bytes,2,opt,name=GroupUUID,proto3" json:"GroupUUID,omitempty"`
	PubKey               *simplcrypto.SerializablePubKey `protobuf:"bytes,3,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	AuthHashSignature    *simplcrypto.Signature          `protobuf:"bytes,4,opt,name=AuthHashSignature,proto3" json:"AuthHashSignature,omitempty"`
	Timestamp            int64                           `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *AuthMemberRequest) Reset()         { *m = AuthMemberRequest{} }
func (m *AuthMemberRequest) String() string { return proto.CompactTextString(m) }
func (*AuthMemberRequest) ProtoMessage()    {}
func (*AuthMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *AuthMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMemberRequest.Unmarshal(m, b)
}
func (m *AuthMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMemberRequest.Marshal(b, m, deterministic)
}
func (m *AuthMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMemberRequest.Merge(m, src)
}
func (m *AuthMemberRequest) XXX_Size() int {
	return xxx_messageInfo_AuthMemberRequest.Size(m)
}
func (m *AuthMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMemberRequest proto.InternalMessageInfo

func (m *AuthMemberRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *AuthMemberRequest) GetGroupUUID() string {
	if m != nil {
		return m.GroupUUID
	}
	return ""
}

func (m *AuthMemberRequest) GetPubKey() *simplcrypto.SerializablePubKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *AuthMemberRequest) GetAuthHashSignature() *simplcrypto.Signature {
	if m != nil {
		return m.AuthHashSignature
	}
	return nil
}

func (m *AuthMemberRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type AuthMemberResponse struct {
	EncChallenge         *simplcrypto.Message            `protobuf:"bytes,1,opt,name=EncChallenge,proto3" json:"EncChallenge,omitempty"`
	MasterPubKey         *simplcrypto.SerializablePubKey `protobuf:"bytes,2,opt,name=MasterPubKey,proto3" json:"MasterPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *AuthMemberResponse) Reset()         { *m = AuthMemberResponse{} }
func (m *AuthMemberResponse) String() string { return proto.CompactTextString(m) }
func (*AuthMemberResponse) ProtoMessage()    {}
func (*AuthMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *AuthMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMemberResponse.Unmarshal(m, b)
}
func (m *AuthMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMemberResponse.Marshal(b, m, deterministic)
}
func (m *AuthMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMemberResponse.Merge(m, src)
}
func (m *AuthMemberResponse) XXX_Size() int {
	return xxx_messageInfo_AuthMemberResponse.Size(m)
}
func (m *AuthMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMemberResponse proto.InternalMessageInfo

func (m *AuthMemberResponse) GetEncChallenge() *simplcrypto.Message {
	if m != nil {
		return m.EncChallenge
	}
	return nil
}

func (m *AuthMemberResponse) GetMasterPubKey() *simplcrypto.SerializablePubKey {
	if m != nil {
		return m.MasterPubKey
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthMemberRequest)(nil), "taask.server.service.AuthMemberRequest")
	proto.RegisterType((*AuthMemberResponse)(nil), "taask.server.service.AuthMemberResponse")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0x4b, 0x3b, 0x31,
	0x10, 0x65, 0xdb, 0xfe, 0x0a, 0x4d, 0x7b, 0xf9, 0x05, 0xc5, 0x45, 0x3c, 0x2c, 0x05, 0xb1, 0x17,
	0x77, 0xa5, 0x5e, 0xf4, 0xa8, 0xb6, 0xa8, 0x48, 0x41, 0x52, 0x7b, 0xf1, 0x96, 0x0d, 0xc3, 0x6e,
	0xe8, 0x66, 0x13, 0xf3, 0x47, 0xac, 0xdf, 0xc3, 0x6f, 0xe8, 0x07, 0x11, 0x93, 0x4a, 0xbb, 0x7a,
	0xe9, 0x25, 0x09, 0x33, 0xf3, 0xe6, 0xcd, 0xcb, 0x3c, 0x34, 0x60, 0x52, 0x08, 0x59, 0xa7, 0x4a,
	0x4b, 0x2b, 0xf1, 0x9e, 0xa5, 0xd4, 0x2c, 0x53, 0x03, 0xfa, 0x15, 0xb4, 0xbf, 0x38, 0x83, 0xc3,
	0xb3, 0x82, 0xdb, 0xd2, 0xe5, 0x29, 0x93, 0x22, 0x63, 0xb2, 0xe4, 0x6f, 0x99, 0xe1, 0x42, 0x55,
	0x4c, 0xaf, 0x94, 0x95, 0x99, 0x47, 0x66, 0x4b, 0x58, 0x29, 0xca, 0x75, 0xe8, 0xb3, 0x13, 0x42,
	0x80, 0x31, 0xb4, 0x80, 0x80, 0x18, 0x7e, 0x46, 0xe8, 0xff, 0x95, 0xb3, 0xe5, 0x0c, 0x44, 0x0e,
	0x9a, 0xc0, 0x8b, 0x03, 0x63, 0x31, 0x46, 0x9d, 0xc5, 0xe2, 0x7e, 0x12, 0x47, 0x49, 0x34, 0xea,
	0x11, 0xff, 0xc6, 0x47, 0xa8, 0x77, 0xab, 0xa5, 0x53, 0x3e, 0xd1, 0xf2, 0x89, 0x4d, 0x00, 0x5f,
	0xa0, 0xee, 0xa3, 0xcb, 0x1f, 0x60, 0x15, 0xb7, 0x93, 0x68, 0xd4, 0x1f, 0x27, 0xa9, 0x67, 0x4e,
	0x03, 0x75, 0x3a, 0x07, 0xcd, 0x69, 0xc5, 0xdf, 0x69, 0x5e, 0x41, 0xa8, 0x23, 0xeb, 0x7a, 0x3c,
	0x0d, 0x03, 0xdc, 0x51, 0x53, 0xce, 0x79, 0x51, 0x53, 0xeb, 0x34, 0xc4, 0x1d, 0xdf, 0xe4, 0xe0,
	0x57, 0x93, 0x9f, 0x34, 0xf9, 0x8b, 0xf8, 0x1e, 0xef, 0x89, 0x0b, 0x30, 0x96, 0x0a, 0x15, 0xff,
	0x4b, 0xa2, 0x51, 0x9b, 0x6c, 0x02, 0xc3, 0x8f, 0x08, 0xe1, 0x6d, 0x99, 0x46, 0xc9, 0xda, 0x00,
	0xbe, 0x44, 0x83, 0x69, 0xcd, 0x6e, 0x4a, 0x5a, 0x55, 0x50, 0x17, 0xe0, 0xf5, 0xf6, 0xc7, 0xfb,
	0x4d, 0xda, 0x59, 0xf8, 0x30, 0xd2, 0x28, 0xc5, 0x13, 0x34, 0x98, 0x51, 0x63, 0x41, 0xaf, 0x65,
	0xb7, 0x76, 0x94, 0xdd, 0x40, 0x5d, 0x9f, 0x3c, 0x1f, 0x6f, 0xad, 0xcc, 0xbb, 0x20, 0x9c, 0xa7,
	0xc1, 0x0b, 0xd9, 0xda, 0x0b, 0x79, 0xd7, 0xaf, 0xeb, 0xfc, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x74,
	0x3f, 0xc7, 0x7f, 0x38, 0x02, 0x00, 0x00,
}
