// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
	proto1 "model/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4e, 0x86, 0x30,
	0x10, 0x85, 0xd3, 0x85, 0x9a, 0xbf, 0x7f, 0x70, 0xd1, 0x18, 0x43, 0x58, 0xab, 0x89, 0x2e, 0x0a,
	0xc1, 0x1b, 0xe8, 0xc6, 0x2d, 0xc5, 0x15, 0xbb, 0x8a, 0x13, 0x24, 0x08, 0xc5, 0x4e, 0xeb, 0xc5,
	0x3c, 0x86, 0x97, 0x32, 0x6d, 0xc1, 0x40, 0x52, 0x13, 0x77, 0xcd, 0xbc, 0x6f, 0xde, 0x9b, 0xe9,
	0xd0, 0x04, 0x41, 0x7f, 0xf6, 0x2d, 0xf0, 0x59, 0x2b, 0xa3, 0xd8, 0x85, 0x91, 0x12, 0x07, 0xee,
	0x8a, 0xa0, 0xf9, 0xa2, 0x65, 0x97, 0xa3, 0x7a, 0x85, 0xf7, 0xdc, 0x23, 0xb9, 0x71, 0x80, 0x7f,
	0x66, 0xe9, 0xb6, 0xae, 0xed, 0x34, 0x81, 0x0e, 0x4a, 0xf9, 0x45, 0xe8, 0xf1, 0x59, 0xe2, 0x50,
	0x07, 0x07, 0xf6, 0x44, 0x4f, 0x2a, 0x0b, 0x16, 0x58, 0xca, 0x77, 0x09, 0xde, 0x80, 0x3b, 0x32,
	0xbb, 0x8e, 0x29, 0xbe, 0xc9, 0xc9, 0x02, 0x70, 0x56, 0x13, 0x02, 0x6b, 0xe8, 0xe1, 0xf1, 0x0d,
	0xda, 0xc1, 0x15, 0xd9, 0x55, 0xac, 0xe7, 0x57, 0x16, 0xf0, 0x61, 0x01, 0x4d, 0xdc, 0x79, 0x43,
	0x05, 0xe7, 0x82, 0x94, 0xdf, 0x84, 0x26, 0xc2, 0xaf, 0xb1, 0xce, 0xdd, 0xd1, 0x73, 0x01, 0x5d,
	0x8f, 0x06, 0x74, 0x10, 0xd8, 0x6d, 0xcc, 0x6c, 0xcf, 0xac, 0xb9, 0x77, 0xff, 0x41, 0x97, 0xb5,
	0x2a, 0x7a, 0xac, 0x8d, 0x06, 0x39, 0xba, 0x91, 0x90, 0xdd, 0xc4, 0x5a, 0x37, 0xc0, 0x1a, 0xf1,
	0xe7, 0x77, 0x16, 0xe4, 0xe1, 0xd0, 0x9c, 0x2d, 0x07, 0x7c, 0x39, 0xf5, 0x57, 0xb9, 0xff, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x79, 0x67, 0x38, 0x3e, 0xee, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	Queue(ctx context.Context, in *proto1.Task, opts ...grpc.CallOption) (*proto1.QueueTaskResponse, error)
	CheckTask(ctx context.Context, in *proto1.CheckTaskRequest, opts ...grpc.CallOption) (TaskService_CheckTaskClient, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) Queue(ctx context.Context, in *proto1.Task, opts ...grpc.CallOption) (*proto1.QueueTaskResponse, error) {
	out := new(proto1.QueueTaskResponse)
	err := c.cc.Invoke(ctx, "/taask.server.service.TaskService/Queue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CheckTask(ctx context.Context, in *proto1.CheckTaskRequest, opts ...grpc.CallOption) (TaskService_CheckTaskClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TaskService_serviceDesc.Streams[0], "/taask.server.service.TaskService/CheckTask", opts...)
	if err != nil {
		return nil, err
	}
	x := &taskServiceCheckTaskClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaskService_CheckTaskClient interface {
	Recv() (*proto1.CheckTaskResponse, error)
	grpc.ClientStream
}

type taskServiceCheckTaskClient struct {
	grpc.ClientStream
}

func (x *taskServiceCheckTaskClient) Recv() (*proto1.CheckTaskResponse, error) {
	m := new(proto1.CheckTaskResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	Queue(context.Context, *proto1.Task) (*proto1.QueueTaskResponse, error)
	CheckTask(*proto1.CheckTaskRequest, TaskService_CheckTaskServer) error
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_Queue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Queue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taask.server.service.TaskService/Queue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Queue(ctx, req.(*proto1.Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CheckTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(proto1.CheckTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskServiceServer).CheckTask(m, &taskServiceCheckTaskServer{stream})
}

type TaskService_CheckTaskServer interface {
	Send(*proto1.CheckTaskResponse) error
	grpc.ServerStream
}

type taskServiceCheckTaskServer struct {
	grpc.ServerStream
}

func (x *taskServiceCheckTaskServer) Send(m *proto1.CheckTaskResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taask.server.service.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Queue",
			Handler:    _TaskService_Queue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckTask",
			Handler:       _TaskService_CheckTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}

// RunnerServiceClient is the client API for RunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RunnerServiceClient interface {
	RegisterRunner(ctx context.Context, in *proto1.RegisterRunnerRequest, opts ...grpc.CallOption) (*proto1.RegisterRunnerResponse, error)
	StreamTasks(ctx context.Context, in *proto1.StreamTasksRequest, opts ...grpc.CallOption) (RunnerService_StreamTasksClient, error)
}

type runnerServiceClient struct {
	cc *grpc.ClientConn
}

func NewRunnerServiceClient(cc *grpc.ClientConn) RunnerServiceClient {
	return &runnerServiceClient{cc}
}

func (c *runnerServiceClient) RegisterRunner(ctx context.Context, in *proto1.RegisterRunnerRequest, opts ...grpc.CallOption) (*proto1.RegisterRunnerResponse, error) {
	out := new(proto1.RegisterRunnerResponse)
	err := c.cc.Invoke(ctx, "/taask.server.service.RunnerService/RegisterRunner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) StreamTasks(ctx context.Context, in *proto1.StreamTasksRequest, opts ...grpc.CallOption) (RunnerService_StreamTasksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RunnerService_serviceDesc.Streams[0], "/taask.server.service.RunnerService/StreamTasks", opts...)
	if err != nil {
		return nil, err
	}
	x := &runnerServiceStreamTasksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RunnerService_StreamTasksClient interface {
	Recv() (*proto1.Task, error)
	grpc.ClientStream
}

type runnerServiceStreamTasksClient struct {
	grpc.ClientStream
}

func (x *runnerServiceStreamTasksClient) Recv() (*proto1.Task, error) {
	m := new(proto1.Task)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RunnerServiceServer is the server API for RunnerService service.
type RunnerServiceServer interface {
	RegisterRunner(context.Context, *proto1.RegisterRunnerRequest) (*proto1.RegisterRunnerResponse, error)
	StreamTasks(*proto1.StreamTasksRequest, RunnerService_StreamTasksServer) error
}

func RegisterRunnerServiceServer(s *grpc.Server, srv RunnerServiceServer) {
	s.RegisterService(&_RunnerService_serviceDesc, srv)
}

func _RunnerService_RegisterRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.RegisterRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).RegisterRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taask.server.service.RunnerService/RegisterRunner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).RegisterRunner(ctx, req.(*proto1.RegisterRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_StreamTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(proto1.StreamTasksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServiceServer).StreamTasks(m, &runnerServiceStreamTasksServer{stream})
}

type RunnerService_StreamTasksServer interface {
	Send(*proto1.Task) error
	grpc.ServerStream
}

type runnerServiceStreamTasksServer struct {
	grpc.ServerStream
}

func (x *runnerServiceStreamTasksServer) Send(m *proto1.Task) error {
	return x.ServerStream.SendMsg(m)
}

var _RunnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taask.server.service.RunnerService",
	HandlerType: (*RunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRunner",
			Handler:    _RunnerService_RegisterRunner_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTasks",
			Handler:       _RunnerService_StreamTasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
