apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: taask-server
  labels: &DeploymentLabels
    io.taask/component: taask-server
spec:
  selector:
    matchLabels: *DeploymentLabels
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *DeploymentLabels
    spec:
      containers:
      - name: taask-server
        image: taask/server:{{ .Values.Tag }}
        command: ["/taask/taask-server"]
        imagePullPolicy: IfNotPresent
        # args: []
        ports:
        - containerPort: 3687
        - containerPort: 3688
        - containerPort: 3689
        - containerPort: 6060
        volumeMounts:
        - mountPath: /taask/config
          name: taask-config
      volumes:
      - name: taask-config
        hostPath:
          # directory location on host
          path: {{ .Values.HomeDir }}/.taask/server/config
          # this field is optional
          type: Directory
---
  
apiVersion: v1
kind: Service
metadata:
  name: taask-server
  labels:
    io.taask/service: taask-server
spec:
  selector:
      io.taask/component: taask-server
  ports:
  - name: runner
    port: 3687
  - name: metrics
    port: 3689

---

apiVersion: v1
kind: Service
metadata:
  name: taask-server-ingress
  labels:
    io.taask/service: taask-server
spec:
  ports:
  - name: task
    port: 3688
    protocol: TCP
    nodePort: 30688
  - name: pprof
    port: 6060
    protocol: TCP
    nodePort: 30600
  selector:
    io.taask/component: taask-server
  type: NodePort