apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: taask-server{{ .Values.Suffix }}
  labels: &DeploymentLabels
    io.taask/manager: server{{ .Values.Suffix }}
    io.taask/component: server
spec:
  selector:
    matchLabels: *DeploymentLabels
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *DeploymentLabels
    spec:
      containers:
      - name: taask-server
        image: taask/server:{{ .Values.Tag }}
        command: ["/taask/taask-server"]
        imagePullPolicy: IfNotPresent
        # args: []
        ports:
        - containerPort: 3687
        - containerPort: 3688
        - containerPort: 3689
        - containerPort: 3690
        # - containerPort: 6060
        volumeMounts:
        - mountPath: /root/.taask/server/config
          name: taask-config
        env:
        - name: "TAASK_PARTNER_HOST"
          value: {{ .Values.PartnerHost }}
      volumes:
      - name: taask-config
        hostPath:
          # directory location on host
          path: {{ .Values.HomeDir }}/.taask/server/config
          # this field is optional
          type: Directory
---
  
apiVersion: v1
kind: Service
metadata:
  name: taask-server-internal
  labels:
    io.taask/service: server
spec:
  selector:
      io.taask/component: server
  ports:
  - name: runner
    port: 3687
  - name: metrics
    port: 3689

---
  
apiVersion: v1
kind: Service
metadata:
  name: taask-server-manager{{ .Values.Suffix }}
  labels:
    io.taask/service: server-manager{{ .Values.Suffix }}
spec:
  selector:
      io.taask/manager: server{{ .Values.Suffix }}
  ports:
  - name: partner
    port: 3690

---

apiVersion: v1
kind: Service
metadata:
  name: taask-server-ingress
  labels:
    io.taask/component: server
spec:
  type: NodePort
  ports:
  - name: task
    port: 3688
    protocol: TCP
    nodePort: 30688
  # - name: pprof
  #   port: 6060
  #   protocol: TCP
  #   nodePort: 30600
  selector:
    io.taask/component: server