// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package crypto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	KeyType              string   `protobuf:"bytes,2,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
	KID                  string   `protobuf:"bytes,3,opt,name=KID,proto3" json:"KID,omitempty"`
	IV                   string   `protobuf:"bytes,4,opt,name=IV,proto3" json:"IV,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetKeyType() string {
	if m != nil {
		return m.KeyType
	}
	return ""
}

func (m *Message) GetKID() string {
	if m != nil {
		return m.KID
	}
	return ""
}

func (m *Message) GetIV() string {
	if m != nil {
		return m.IV
	}
	return ""
}

type Signature struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=Signature,proto3" json:"Signature,omitempty"`
	KID                  string   `protobuf:"bytes,2,opt,name=KID,proto3" json:"KID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Signature) GetKID() string {
	if m != nil {
		return m.KID
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "taask.server.crypto.Message")
	proto.RegisterType((*Signature)(nil), "taask.server.crypto.Signature")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2e, 0x49, 0x4c, 0x2c, 0xce,
	0xd6, 0x2b, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x4b, 0x2e, 0xaa, 0x2c, 0x28, 0xc9, 0x57, 0x8a,
	0xe4, 0x62, 0xf7, 0x85, 0xa8, 0x12, 0x12, 0xe2, 0x62, 0x71, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0xbd, 0x53, 0x2b, 0x43, 0x2a, 0x0b,
	0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x01, 0x2e, 0x66, 0x6f, 0x4f,
	0x17, 0x09, 0x66, 0xb0, 0x28, 0x88, 0x29, 0xc4, 0xc7, 0xc5, 0xe4, 0x19, 0x26, 0xc1, 0x02, 0x16,
	0x60, 0xf2, 0x0c, 0x53, 0xb2, 0xe6, 0xe2, 0x0c, 0xce, 0x4c, 0xcf, 0x4b, 0x2c, 0x29, 0x2d, 0x4a,
	0x15, 0x92, 0x41, 0xe2, 0x40, 0x6d, 0x40, 0x92, 0x85, 0x1a, 0xc6, 0x04, 0x37, 0xcc, 0x49, 0x2d,
	0x4a, 0x25, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0xec, 0x72, 0x08,
	0xa9, 0x0b, 0x71, 0xbf, 0x3e, 0xc4, 0xfd, 0x49, 0x6c, 0x60, 0xbf, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x39, 0xd0, 0xa8, 0xe9, 0xec, 0x00, 0x00, 0x00,
}
